list() return all drives
larrybahr/windows-network-drive pull request #25
Opened 2022-06-20 06:20 UTC by nytamin

Closes #24 

This PR changes how list() fetches drives. It'll now return all drives with status info, not only the ones with OK status.

This is a **BREAKING CHANGE**:
Return type of list() has changed, from a key-value with strings to a key-value with objects containing statuses and path.
Return type of find() has changed, from a string to an object containing statuses and path.

Notes: 
* I have tested this to work locally and the unit tests pass locally
* The README mentions linting and formatting using VS Code. But no linter, linting-rules or formatting-rules are defined, so I haven't done this.

2022-06-22 04:11 UTC, larrybahr requested changes
Thank you for the great improvements! You did a good job writing new test cases and I enjoyed looking over your work.

I have a couple small suggestions that I would like to hear your thoughts on.

2022-06-22 04:11 UTC, larrybahr commented on index.js
> +	 * @returns {Promise<Object>} - Object keys are drive letters, values are { ok: boolean, path: string }
What about `statusString`

2022-06-22 04:11 UTC, larrybahr commented on index.d.ts
> +  function find(drivePath: string): Promise<{
Since this in now a more complex object, it could make sense to have a single interface that both `find` and `list` return. Maybe something like
``` typescript
interface driveInfo {
    /** Status of the network drive. A falsy value might indicate connectivity issues */
    status: boolean

    /** Drive letter */
    driveLetter: string

    /** Path to the network drive */
    path: string

    /**
     * Status string, describing the status of the network drive.
     * This is a textual value depending on the local Windows system language.
     */
    statusMessage: string
}
```

2022-06-22 04:11 UTC, larrybahr commented on index.js
> +	 list: function list()
Looks like some extra white space. VSCode has a default formatter that I use. This is a small project so using the built in one just made more sense at the time.

2022-06-22 04:11 UTC, larrybahr commented on index.js
> +					.map((l) => l.replace(/[\r\n]/g, '')) // Trim line endings
IMHO single letter vars lead to confusion in the long term. Could we change `l` to `line`?

When possible I prefer self documenting code. In this case there is a built in method that does exactly what you want `line.trim()` so you do not need the regex.

2022-06-22 04:11 UTC, larrybahr commented on index.js
> +					.filter(Boolean) // Remove empty lines
You would not need the comment if you did something like `line => line.length !== 0`

2022-06-22 04:11 UTC, larrybahr commented on index.js
> +				const lines = `${result.stdout}`
Why is this wrapped in a template literal? Could you just use `result.stdout`?

2022-06-22 04:11 UTC, larrybahr commented on index.js
> +						// const network = m[4].trim();
Why have commented out code? If this is useful info you should just return it.

2022-06-22 04:11 UTC, larrybahr commented on index.js
> +				for (let i = 0; i< lines.length; i++) {
`i` => `index`

2022-06-22 04:11 UTC, larrybahr commented on index.js
> +				for (let i = 0; i< lines.length; i++) {
`i` => `index`

2022-06-22 04:11 UTC, larrybahr commented on index.js
> +					const m = line.match(/^(.+) +(\w): +([^ ]+) +(.+)$/);
`m` => `matches`

2022-06-22 04:11 UTC, larrybahr commented on test/test.js
> +					for (let i = 0; i < driveLetters.length; i++) {
`i` => `index`

2022-06-22 04:11 UTC, larrybahr commented on test/test.js
> +					if (!firstResult) {
I would do an explicit type check here `'object' === typeof firstResult`

2022-06-22 04:11 UTC, larrybahr commented on test/test.js
> +					if (firstResult.status !== Boolean(firstResult.status)) {
What about `typeof firstResult.status !== 'boolean'`

2022-06-22 04:11 UTC, larrybahr commented on test/test.js
> +					const firstResult = driveList[driveLetters[0]];
Why only check the first result? Since you are already looping over the drive letters you could do these checks in the same loop.

2022-06-22 04:12 UTC, larrybahr commented
Also feel free to add yourself as a contributor https://github.com/larrybahr/windows-network-drive/blob/master/package.json#L11

2022-06-22 07:19 UTC, nytamin commented on index.js
> +	 * @returns {Promise<Object>} - Object keys are drive letters, values are { ok: boolean, path: string }
You're correct, of course. I'll fix!

2022-06-22 07:20 UTC, nytamin commented on index.d.ts
> +  function find(drivePath: string): Promise<{
Good idea!

2022-06-22 07:21 UTC, nytamin commented on index.js
> +	 list: function list()
I was able to figure out which formatter is the default (I'm using Prettier locally, it had to be disabled for the default to take over). I also took the liberty of updating the README to clarify which formatter to use.

2022-06-22 07:26 UTC, nytamin commented on index.js
> +					.map((l) => l.replace(/[\r\n]/g, '')) // Trim line endings
sure, good points!

2022-06-22 07:32 UTC, nytamin commented on index.js
> +				const lines = `${result.stdout}`
Out of habit, I suppose.
It's a way to guard for the case where stdout is not a string (ie a Buffer).

2022-06-22 07:35 UTC, nytamin commented on index.js
> +						// const network = m[4].trim();
The only value I've seen in this field is "Microsoft Windows Network", I don't really see the use for it, but if you think it's useful I can include it.

2022-06-22 07:41 UTC, nytamin commented on test/test.js
> +					const firstResult = driveList[driveLetters[0]];
Since there is a check just above that asserts the length to be 1, I didn't see the point.

2022-06-22 07:49 UTC, nytamin commented on index.js
> +					.filter(Boolean) // Remove empty lines
I'm inclined to leave this as-is, tbh.
`.filter(Boolean)` is the safest way of removing falsy values and I think that the verbosity in the comments for these operations are important to follow what's happening.

2022-06-22 07:52 UTC, nytamin commented
@larrybahr Thanks for the thorough review!
I've addressed and fixed most of your comments, please have another look and let me know if there's anything left you feel particularly strongly about.

2022-07-04 03:23 UTC, larrybahr reviewed
Thank you for making the changes. I think it looks great overall. I just want to confirm the tests are good before I accept (see note). Everything else looks good!

2022-07-04 03:23 UTC, larrybahr commented on test/test.js
> +					const firstResult = driveList[driveLetters[0]];
I am on a small screen so I may have missed it, but I do not see an assertion that forces it to be 1 and only 1. I do see an assertion that will make sure we have at least 1 result.

2022-07-04 03:23 UTC, larrybahr commented on index.js
> +					.filter(Boolean) // Remove empty lines
Fair enough :+1:

2022-07-04 03:24 UTC, larrybahr commented
FYI, I added automated tests via github actions that should run if/when you push to this PR. :crossed_fingers: they run.

2022-07-04 04:22 UTC, larrybahr requested changes
More minor changes:
* The README.md needs updated (see notes)
* The examples in `example/write-a-file-to-a-network-drive/index.js` also need to be updated since the interface is changing

2022-07-04 04:22 UTC, larrybahr commented on README.md
The list and find docs in the ReadMe.md need to be updated

2022-07-04 05:29 UTC, nytamin commented
good points! I've updated the docs and example

2022-07-04 13:24 UTC, larrybahr commented
Thank you for your hard work/many revisions :handshake: . Everything looks great!
I will merge this and work on releasing it.

2022-07-04 13:25 UTC, merged

2022-07-04 13:56 UTC, larrybahr commented
V4.0.0 is live on NPM with this change